config/routes.rb
Rails.application.routes.draw do

  # ----------------------------------------------------------
    # Links
  # ----------------------------------------------------------

  resources :links , except: [:edit, :show ] do
    member do
      get 'favourite'
      get 'update_description'
    end
  end
  get 'favourites' => 'links#favourites'
  
  # ----------------------------------------------------------
    # Collections
  # ----------------------------------------------------------

  resources :collections, except: [:edit, :show ] do
    member do
      get 'pin'
      delete 'unfollow'
    end
  end

  get "browse/:collection_id" => "collections#browse", :as => "browse"
  get "browse/:collection_id/new_collection" => "collections#new", :as => "new_sub_collection"
  get "browse/:collection_id/new_link" => "links#new", :as => "new_sub_link"

  post "collection/share" => "collections#share"

  # ----------------------------------------------------------
    # Devise
  # ----------------------------------------------------------

  devise_for :users
  devise_scope :user do 
      get 'register', to: "devise/registrations#new"
      get 'login', to: "devise/sessions#new"
  end

  # ----------------------------------------------------------
    # Where users go upon opening site
  # ----------------------------------------------------------

  authenticated :user do
    get '/', to: "collections#index"
  end
  unauthenticated :user do
    root to: 'static_pages#home' 
  end

  # ----------------------------------------------------------
    # Static Pages
  # ----------------------------------------------------------
  get 'home' => 'static_pages#home', as: :home


end

app/models/collection.rb
class Collection < ActiveRecord::Base


# ------------------------------------------------------------------------------
# Includes & Extensions
# ------------------------------------------------------------------------------



# ------------------------------------------------------------------------------
# Constants
# ------------------------------------------------------------------------------



# ------------------------------------------------------------------------------
# Attributes
# ------------------------------------------------------------------------------



# ------------------------------------------------------------------------------
# Associations
# ------------------------------------------------------------------------------

belongs_to :user
has_many :shared_collections, :dependent => :destroy
has_many :links , :dependent => :destroy
has_many :pins , :dependent => :destroy

# ------------------------------------------------------------------------------
# Validations
# ------------------------------------------------------------------------------

  # validates :title, :presence => true


# ------------------------------------------------------------------------------
# Callbacks
# ------------------------------------------------------------------------------

after_save :set_default_title
after_save :assign_shared_collections

# ------------------------------------------------------------------------------
# Nested Attributes
# ------------------------------------------------------------------------------

accepts_nested_attributes_for :shared_collections

# ------------------------------------------------------------------------------
# Scopes
# ------------------------------------------------------------------------------



# ------------------------------------------------------------------------------
# Other
# ------------------------------------------------------------------------------

acts_as_tree     # Nested collections



# ------------------------------------------------------------------------------
# Class Methods
# ------------------------------------------------------------------------------

def set_default_title    # Self explanatary 
	if self.title.empty?
		self.title = "Collection ##{self.id}"
		self.save
	end
end

def assign_shared_collections   # On creation, assigns any users in parent collection to also have access
	
	if self.parent
		collection_parent = self.parent 
		shared_collections = SharedCollection.where(collection_id: collection_parent.id)
		shared_user_ids = shared_collections.pluck(:shared_user_id)

		shared_user_ids.each do |current_user_id|
			@shared_collection = SharedCollection.new
			@shared_collection.collection_id = self.id

			if current_user_id == self.user_id    # Non owner of parent creates a collection inside parent, allows the creator to see inside, by creating shared collection record
				@shared_collection.user_id = self.user_id
				@shared_collection.shared_user_id = collection_parent.user_id
				@shared_collection.shared_email = User.where(id: collection_parent.user_id).first.email

			else	# Assigning all shared users of parent to children created by owner of parent
				@shared_collection.user_id = collection_parent.user_id
				@shared_collection.shared_user_id = current_user_id
				@shared_collection.shared_email = User.where(id: current_user_id).first.email
			end

			@shared_collection.save
		end

	else
	end

end

# ------------------------------------------------------------------------------
# Instance Methods
# ------------------------------------------------------------------------------



# ------------------------------------------------------------------------------
protected
# ------------------------------------------------------------------------------


# ------------------------------------------------------------------------------
private
# ------------------------------------------------------------------------------




end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController

	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	# CALLBACKS 
	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	 
	before_action :set_collection, only: [:show, :edit, :update, :destroy, :unfollow, :pin]
	before_action :sidebar_collections, only: [:index, :show, :new, :edit, :browse]


	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	# GET : index
	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	 
	def index 
		@bottom_bar_header = "Dock"
		
		if current_user


		#show collections shared by others but only the top level
		@all_shared_collections = current_user.shared_collections_by_others
		@being_shared_collections =[]

		unless @all_shared_collections.nil?
			@all_shared_collections.each do |shared_collection|

				@being_shared_collections.push(shared_collection) unless current_user.has_share_access?(shared_collection.parent) 

			end
		end

		#show only root collections 
		@collections = current_user.collections.roots.reverse

		#show only root files 
		@links = current_user.links.where("collection_id is NULL").reverse  
		end

	end


	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	# GET : show
	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	 
	def show
	end

	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	# GET : new
	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	 
	def new
		@bottom_bar_header = "New Collection"

		@collection = current_user.collections.new     

		#if there is "collection_id" param, we know that we are under a collection, thus, we will essentially create a subcollection 
		if params[:collection_id] #if we want to create a collection inside another collection 

			#we still need to set the @current_collection to make the buttons working fine 
			@current_collection = Collection.find(params[:collection_id]) 

			#then we make sure the collection we are creating has a parent collection which is the @current_collection 
			@collection.parent_id = @current_collection.id 
		end
	end

	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	# GET : edit
	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------

	def edit
	end

	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	# POST : create
	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	 
	def create 
		@collection = current_user.collections.new(collection_params) 
		if @collection.save 
			flash[:success] = "collection created!"
			redirect_to browse_path(@collection)  #then we redirect to the parent collection 
		else
			render :action => 'new'
		end
	end


	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	# PUT : update
	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	 
	def update
		respond_to do |format|
			if @collection.update(collection_params)
				format.html { redirect_to @collection}
				format.json { render :show, status: :ok, location: @collection }
			else
				format.html { render :edit }
				format.json { render json: @collection.errors, status: :unprocessable_entity }
			end
		end
	end

	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	# DELETE : destroy
	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	 
	def destroy 
		@parent_collection = @collection.parent #grabbing the parent collection 
		#this will destroy the collection along with all the contents inside 
		#sub collections will also be deleted too as well as all files inside 

		# Destroy links in current colleciton
		@collection.links.each do |link|
			link.user_id = nil
			link.save
		end

		# Destroy any links in current collections descendants
		@collection.descendants.each do |collection|
			collection.links.each do |link|
				link.user_id = nil
				link.save
			end
			collection.user_id = nil
			collection.save
		end

		@collection.user_id = nil
		@collection.save
		#redirect to a relevant path depending on the parent collection 
		if @parent_collection
			flash[:success] = "collection removed!"
			redirect_to browse_path(@parent_collection) 
		else
			redirect_to root_url       
		end
	end

	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	# GET : pin
	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------

	def pin

		if Pin.where(user_id: current_user.id, collection_id: @collection.id).present?
			@pin = Pin.where(user_id: current_user.id, collection_id: @collection.id)
			@pin.first.delete
		else
			@pin = @collection.pins.new(user: current_user)
			@pin.save
		end 

	end

	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	# GET : browse
	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	 

	def browse 

		#first find the current collections within own collections 
		@current_collection = current_user.collections.find_by_id(params[:collection_id])   
		@is_this_collection_being_shared = false if @current_collection #just an instance variable to help hiding buttons on View 


		#if not found in own collections, find it in being_shared_collections 
		if @current_collection.nil? 
			collection = Collection.find_by_id(params[:collection_id]) 

			@current_collection ||= collection if current_user.has_share_access?(collection)
			@is_this_collection_being_shared = true if @current_collection #just an instance variable to help hiding buttons on View 
		end

		#array of shared collection records with current collection id
		all_shared_collections_current = SharedCollection.where(collection_id: @current_collection.id) 
		#remove any records where user isn't signed up
		@shared_collections_current_filtered = all_shared_collections_current.where.not(shared_user_id: nil) 

		if @current_collection
			@being_shared_collections = []
			@bottom_bar_header = @current_collection.title

			#show collections under this current collection, but not load ones current user has been removed from
			@collections = []
			@current_collection.children.each do |collection|
				if current_user.has_share_access?(collection)
					@collections.push(collection)
				else
				end
			end

			#show only files under this current collection 
			@links = @current_collection.links.reverse
			render :index
		else
			redirect_to root_url 
		end

	end

	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	# POST : share
	# ---------------------------------------------------------------------------------------------------------------------------------------------------------------
	 
	def share
		#first, we need to separate the emails with the comma 
		email_addresses = params[:email_addresses].split(",") 

		email_addresses.each do |email_address| 

			shared_user = User.find_by_email(email_address) 

			#save the details in the Sharecollection table 
			@shared_collection = current_user.shared_collections.new
			@shared_collection.collection_id = params[:collection_id] 
			@shared_collection.shared_email = email_address 
			@shared_collection.shared_user_id = shared_user.id if shared_user 
			@shared_collection.message = params[:message] 

			current_collection = Collection.where(id: params[:collection_id]).first
			current_collection.descendants.each do |descendant|
				@shared_collection_descendant = current_user.shared_collections.new
				@shared_collection_descendant.collection_id = descendant.id
				@shared_collection_descendant.shared_email = email_address 
				@shared_collection_descendant.shared_user_id = shared_user.id if shared_user 
				@shared_collection_descendant.save
			end

			#getting the shared user id right the owner the email has already signed up with ShareBox 
			#if not, the field "shared_user_id" will be left nil for now. 


			# now we need to send email to the Shared User, except if they already exist, and if they are the owners of the parent

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_breadcrumbs.html.erb
<div class="breadcrumbs"> 

	<% if @current_collection %>        
		
		<!-- checking if the collection has a parent -->

		<% if current_page?(:controller => "collections", :action => "new") || current_page?(:controller => "links", :action => "new") %>

			<%= link_to :back do %> 
				<i class="fa fa-arrow-left"></i>
			<% end %> 
			
		<% elsif @current_collection.ancestors == [] %> 
			
			<!-- If no parent, link to root -->
			<%= link_to root_path do %> 
				<i class="fa fa-arrow-left"></i>
			<% end %> 

		<!-- check if current_user has access to parent -->
		<% elsif current_user.has_share_access?(@current_collection.parent)%>
			
			<!-- if user does have access, link to parent -->
			<%= link_to browse_path(@current_collection.parent) do %>
				<i class="fa fa-arrow-left"></i>
			<% end %> 

		<!-- if user doesn't haven't access to parent link to root -->
		<% else %>
			
			<%= link_to root_path do %>
				<i class="fa fa-arrow-left"></i>
			<% end %>  

		<% end %>

	<% elsif current_page?('/') || current_page?('/collections') %>

	<% else #if we are not under any collection%>  

			<%= link_to root_path do %>
				<i class="fa fa-arrow-left"></i>
			<% end %> 


	<% end %>

</div>

app/views/collections/_collection.html.erb
<div class="collection-wrapper left">

	
	<%= render '/collections/pin', collection: collection %>

	<div class="collection-title">

		<%= link_to browse_path(collection) do %>

			<h5><%= collection.title %></h5>

		<% end %>

	</div>

	<div class="collection-links-wrapper">

		<ul>
			<% collection.links.reverse.first(3).each do |link| %>

				<li>

					<a href="<%= link.url %>" onclick="window.open(this.href); return false;" target="_blank">
						<%= link.description %>
					</a>

				</li>

			<% end %>

		</ul>

	</div>

	<div class="collection-users-wrapper">


	</div>


</div>

app/views/collections/_form.html.erb
<%= provide(:title, "New Collection" ) %>

<div class="outer-form">
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field-row">
    <%= f.text_field :title, placeholder: "Enter title of the collection" , autofocus: true  %>
  </div>
  <%= f.hidden_field :parent_id %> 
  <div class="form-actions">
    <%= f.button "Add collection", type: 'submit', class: "form-submit-button", data: { disable_with: 'Submitting' } %>
  </div>
<% end %>
</div>

app/views/collections/_new_collection.html.erb
<%= form_for(@collection) do |f| %>
	  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="collection-wrapper left">

	<div class="collection-title">


			<h5><%= f.text_field :title, placeholder: "new collection", class: "new-collection-form" %></h5>


	</div>

  	<%= f.hidden_field :parent_id %> 


	<div class="collection-links-wrapper">

    		<%= f.button type: 'submit', class: "form-submit-button", data: { disable_with: 'submitting' } do %>

			<i class="fa fa-plus"></i>

    		<% end %>

	</div>
	

	<div class="collection-users-wrapper">


	</div>


</div>

<% end %>

app/views/collections/_pin.html.erb
<!-- This one is the pinned Buttons -->

<%= link_to pin_collection_path(collection), id: dom_id(collection, :pin), class: "collection-pin-link", remote: true  do %>

		<% if Pin.where(user_id: current_user.id, collection_id: collection.id).present? %>

			<div class="collection-pin pin-selected">
				<i class="fa fa-thumb-tack"></i>
			</div>

		<% else %>

			<div class="collection-pin">
				<i class="fa fa-thumb-tack"></i>
			</div>

		<% end %>

<%end%>

app/views/collections/index.html.erb
<% if @current_collection %>
	<%= provide(:title, "#{@current_collection.title}" )%>
<% else %>
	<%= provide(:title, "Dock" ) %>
<% end %>




<!-- Links -->
<% if current_user %>
<% @links.each do |link| %>

	<%= render '/links/link' , link: link %>

<% end %>


<!-- Own Collections -->

<%= render @collections %>


<!-- Listing Shared collections (the collections shared by others) -->

<%= render @being_shared_collections %>

<% end %>

<!-- Invitation form -->

<div id="invitation_form" title="Invite others to share" style="display:none"> 

	<%= form_tag('/collection/share' ) do %> 

		<label for="email_addresses">Enter recipient email addresses here</label><br /><br /> 

		<%= text_field_tag('email_addresses', "", placeholder: "john.snow@gmail.com, stannis@hotmail.co.uk") %><br /><br />  

		<%= text_area_tag( 'message',"",placeholder: "Optional message" )%> 
 
		<%= hidden_field_tag "collection_id" %> 

	<% end %>                 

</div>

app/views/collections/new.html.erb
<%= render 'form' %>

app/views/collections/pin.js.erb
$('#<%= dom_id(@collection, :pin) %>').html("<%= escape_javascript(render 'pin', collection: @collection) %>"); 
$(".sidebar-collection-links-wrapper").load(" .sidebar-collection-links-wrapper");

app/views/collections/share.js.erb
//closing the dialog box 
$("#invitation_form").dialog("close"); 