config/routes.rb
Rails.application.routes.draw do

  # ----------------------------------------------------------
    # Links
  # ----------------------------------------------------------

  resources :links , except: [:edit, :show ] do
    member do
      get 'favourite'
      get 'update_description'
    end
  end
  get 'favourites' => 'links#favourites'
  
  # ----------------------------------------------------------
    # Collections
  # ----------------------------------------------------------

  resources :collections, except: [:edit, :show ] do
    member do
      get 'pin'
      delete 'unfollow'
    end
  end

  get "browse/:collection_id" => "collections#browse", :as => "browse"
  get "browse/:collection_id/new_collection" => "collections#new", :as => "new_sub_collection"
  get "browse/:collection_id/new_link" => "links#new", :as => "new_sub_link"

  post "collection/share" => "collections#share"

  # ----------------------------------------------------------
    # Devise
  # ----------------------------------------------------------

  devise_for :users
  devise_scope :user do 
      get 'register', to: "devise/registrations#new"
      get 'login', to: "devise/sessions#new"
  end

  # ----------------------------------------------------------
    # Where users go upon opening site
  # ----------------------------------------------------------

  authenticated :user do
    get '/', to: "collections#index"
  end
  unauthenticated :user do
    root to: 'static_pages#home' 
  end

  # ----------------------------------------------------------
    # Static Pages
  # ----------------------------------------------------------
  get 'home' => 'static_pages#home', as: :home


end

app/models/link.rb
class Link < ActiveRecord::Base
	
# ------------------------------------------------------------------------------
# Includes & Extensions
# ------------------------------------------------------------------------------



# ------------------------------------------------------------------------------
# Constants
# ------------------------------------------------------------------------------



# ------------------------------------------------------------------------------
# Attributes
# ------------------------------------------------------------------------------



# ------------------------------------------------------------------------------
# Associations
# ------------------------------------------------------------------------------
belongs_to :collection
belongs_to :user
has_many :favourites


# ------------------------------------------------------------------------------
# Validations
# ------------------------------------------------------------------------------

validates_presence_of :url, :description, :message => "can't be empty"
validates_format_of :url, with: URI::regexp(%w(http https)), :message => "must start with http:// or https://"

# ------------------------------------------------------------------------------
# Callbacks
# ------------------------------------------------------------------------------

before_save :sanitize_inputs


# ------------------------------------------------------------------------------
# Nested Attributes
# ------------------------------------------------------------------------------



# ------------------------------------------------------------------------------
# Scopes
# ------------------------------------------------------------------------------



# ------------------------------------------------------------------------------
# Other
# ------------------------------------------------------------------------------



# ------------------------------------------------------------------------------
# Class Methods
# ------------------------------------------------------------------------------


# ------------------------------------------------------------------------------
# Instance Methods
# ------------------------------------------------------------------------------



# ------------------------------------------------------------------------------
protected
# ------------------------------------------------------------------------------

def sanitize_inputs
	self.url.downcase!
	self.description.downcase!
end


# ------------------------------------------------------------------------------
private
# ------------------------------------------------------------------------------




end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:update, :favourite, :update_description]
  # before_action :authenticate_user!, except: [:index, :show]
  before_action :sidebar_collections, only: [:index, :new, :favourites, :create ]



  # GET /links
  # GET /links.json
  # Show all links the user created
  def index
    if current_user
    @links = current_user.links  
    @bottom_bar_header = "My Links"
    end
  end

  # GET /links/new
  def new
    @bottom_bar_header = "New Link"
    @link = current_user.links.new  || guest_user.links.new   
    if params[:collection_id] #if we want to upload a file inside another collection 
     @current_collection = Collection.find(params[:collection_id]) 
     @link.collection_id = @current_collection.id 
    end    
end

  # POST /links
  # POST /links.json
  def create 
  @link = current_user.links.new(link_params) 

  if @link.save 
  
   if @link.collection #checking if we have a parent collection for this file 
     redirect_to browse_path(@link.collection)  #then we redirect to the parent collection 
   else
     redirect_to root_path
   end      
      flash[:success] = "link made!"
  else
    @bottom_bar_header = "Oops! Something went wrong!"
   render :action => 'new'
  end
end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to links_path}
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_description
  end

  # GET /favourites
  # List all favourited links

  def favourites
    @bottom_bar_header = "Favourites"
    @favourited_links =  Link.joins(:favourites).where( favourites: { user_id: current_user } )
  end

  # PUT /link/1/favourite
  #Method to assign like to link

  def favourite
    if Favourite.where(user_id: current_user.id, link_id: @link.id).present?
      @favourite = Favourite.where(user_id: current_user.id, link_id: @link.id)
      @favourite.first.delete
    else
      @favourite = @link.favourites.new(user: current_user)
      @favourite.save
    end 
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy 
  @link = Link.find(params[:id]) 
  @parent_collection = @link.collection #grabbing the parent collection before deleting the record 
  @link.destroy 
  
  #redirect to a relevant path depending on the parent collection 
  if @parent_collection
      flash[:success] = "link destroyed!"

   redirect_to browse_path(@parent_collection) 
  else
    flash[:success] = "link destroyed!"
    redirect_to :back
  end
end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:url, :description, :image_url, :user_id, :collection_id )
    end
end

app/helpers/links_helper.rb
module LinksHelper




	def shortened_url(url)
		url.truncate(50)
	end

	def short_url(url)
		url.truncate(30)
	end


end

app/views/links/_favourite.html.erb
<!-- This one is the Star Buttons -->

<%= link_to favourite_link_path(link), id: dom_id(link, :favourite), remote: true  do %>

		<% if current_user.favourites.where(link_id: link).present? %>

			<div class="link-favourite">

				<i class="fa fa-star"></i>

			</div>

		<% else %>
			<div class="link-favourite">

				<i class="fa fa-star-o"></i>	
			</div>

		<% end %>

<%end%>

app/views/links/_form.html.erb
<%= provide(:title, "New Link" ) %>
<div class="outer-form">

	<%= form_for(@link) do |f| %>

		<% if @link.errors.any? %>

			<div id="error_explanation" class="error-form">

				<ul>
					<% @link.errors.full_messages.each do |message| %>

						<li><%= message %></li>

					<% end %>

				</ul>

			</div>

		<% end %>

		<div class="field-row">
			<%= f.text_field :url , placeholder: "Copy the url here ... https://www.example.com" , autofocus: true %>
		</div>

		<div class="field-row">
			<%= f.text_field :description, placeholder: "Description goes here"  %>
		</div>

		<%= f.hidden_field :collection_id %> 

		<div class="form-actions">
			<%= f.button "add link", type: 'submit', class: "form-submit-button", data: { disable_with: 'Submitting' } %>
		</div>



	<% end %>

</div>

app/views/links/_link.html.erb
<div class="link-wrapper left" id="link-section-id">
	
	<!-- Link mover part -->
	
<!-- 	<div class="link-grabber">

		<i class="fa fa-bars"></i>
	</div> -->
	
	<!-- Favourite link -->
	
	<%= render '/links/favourite', link: link %>


	<!-- Edit the link -->

	<div class="edit-link-button">

		<%= link_to update_description_link_path(link), remote: true do %>

			<i class="fa fa-check edit-icons check-button"></i>

		<% end %>

		<i class="fa fa-pencil-square-o edit-icons edit-button"></i>

	</div>


	<!-- SHOW Part of the link info -->


	<%= render "/links/update_description", link: link %>


	<!-- EDIT Part of the link info -->

	<div class="link-edit-info editable hidden">

		<div class="link-description link-info">

			<h5><%= best_in_place link, :description, :as => :input , :class => "best_in_place_link" %></h5>

		</div>

	</div>

	<!-- DELETE the link button -->

	<%= link_to link, method: :delete, data: { confirm: 'Are you sure?' } do %>

		<div class="delete-link-button">

			<i class="fa fa-times"></i>

		</div>


	<% end %>

	<!-- SHOW URL Button -->

	<div class="show-url-button">

		<i class="fa fa-info-circle"></i>
		
	</div>


	<!-- Link url -->

	<div class="link-url link-info">

		<p><%= link.url%></p>

	</div>

</div>

app/views/links/_link_description.html.erb
<a href="<%= link.url %>" onclick="window.open(this.href); return false;" target="_blank" class="link-show-info editable" >

	<div class="link-description">

		<h5><%= link.description %></h5>

	</div>

</a>

app/views/links/_new_link.html.erb
<%= form_for(@link) do |f| %>
	<% if @link.errors.any? %>

		<div id="error_explanation">

			<h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

			<ul>
				<% @link.errors.full_messages.each do |message| %>

					<li><%= message %></li>

				<% end %>

			</ul>

		</div>

	<% end %>

	<div class="link-wrapper left" id="link-section-id">


		<%= f.button "tick", type: 'submit', class: "link-submit-button left", data: { disable_with: '+' } %>


		<%= f.text_field :description, placeholder: "description" , class: "new-link-description left" %>


		<%= f.text_field :url , placeholder: "url" , class: "new-link-url left"%>



		<%= f.hidden_field :collection_id %> 


	</div>

<% end %>

app/views/links/_update_description.html.erb
<%= content_tag :div , id: dom_id(link, :update_description) , class: "link-show-info editable" do %>

	<a href="<%= link.url %>" onclick="window.open(this.href); return false;" target="_blank" >

		<div class="link-description">

			<h5><%= link.description %></h5>

		</div>

	</a>

<% end %>

app/views/links/favourite.js.erb
$('#<%= dom_id(@link, :favourite) %>').html("<%= escape_javascript(render 'favourite', link: @link) %>"); 

app/views/links/favourites.html.erb
<%= provide(:title, "Favourites" ) %>

<!-- This one is the Favourite Page  -->

<%= render @favourited_links %>

app/views/links/index.html.erb
<%= render @links %>

app/views/links/new.html.erb
<%= render 'form' %>

app/views/links/update_description.js.erb
$('#<%= dom_id(@link, :update_description)%>').html("<%= escape_javascript(render 'update_description', link: @link) %>");