config/routes.rb
Rails.application.routes.draw do

  # ----------------------------------------------------------
    # Links
  # ----------------------------------------------------------

  resources :links , except: [:edit, :show ] do
    member do
      get 'favourite'
      get 'update_description'
    end
  end
  get 'favourites' => 'links#favourites'
  
  # ----------------------------------------------------------
    # Collections
  # ----------------------------------------------------------

  resources :collections, except: [:edit, :show ] do
    member do
      get 'pin'
      delete 'unfollow'
    end
  end

  get "browse/:collection_id" => "collections#browse", :as => "browse"
  get "browse/:collection_id/new_collection" => "collections#new", :as => "new_sub_collection"
  get "browse/:collection_id/new_link" => "links#new", :as => "new_sub_link"

  post "collection/share" => "collections#share"

  # ----------------------------------------------------------
    # Devise
  # ----------------------------------------------------------

  devise_for :users
  devise_scope :user do 
      get 'register', to: "devise/registrations#new"
      get 'login', to: "devise/sessions#new"
  end

  # ----------------------------------------------------------
    # Where users go upon opening site
  # ----------------------------------------------------------

  authenticated :user do
    get '/', to: "collections#index"
  end
  unauthenticated :user do
    root to: 'static_pages#home' 
  end

  # ----------------------------------------------------------
    # Static Pages
  # ----------------------------------------------------------
  get 'home' => 'static_pages#home', as: :home


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_permitted_parameters, if: :devise_controller?
  before_action :current_or_guest_user


  def sidebar_collections
    @sidebar_collections=  Collection.joins(:pins).where( pins: { user_id: current_user } )
  end

  # if user is logged in, return current_user, else return guest_user
  def current_or_guest_user
    if current_user
      if session[:guest_user_id] && session[:guest_user_id] != current_user.id
        # reload guest_user to prevent caching problems before destruction
        guest_user(with_retry = false).reload.try(:destroy)
        session[:guest_user_id] = nil
      end
      current_user
    else
      guest_user
    end
  end

  # find guest_user object associated with the current session,
  # creating one as needed
  def guest_user(with_retry = true)
    # Cache the value the first time it's gotten.
    @cached_guest_user ||= User.find(session[:guest_user_id] ||= create_guest_user.id)

  rescue ActiveRecord::RecordNotFound # if session[:guest_user_id] invalid
     session[:guest_user_id] = nil
     guest_user if with_retry
  end

  private

    def create_guest_user
    u = User.create(:email => "guest_#{Time.now.to_i}#{rand(100)}@example.com")
    u.save!(:validate => false)
    session[:guest_user_id] = u.id
    u
  end


    protected



  def configure_devise_permitted_parameters
    registration_params = [:first_name, :last_name, :email, :password, :password_confirmation]

    if params[:action] == 'update'
      devise_parameter_sanitizer.for(:account_update) { 
        |u| u.permit(registration_params << :current_password)
      }
    elsif params[:action] == 'create'
      devise_parameter_sanitizer.for(:sign_up) { 
        |u| u.permit(registration_params) 
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	  # Returns the full title on a per-page basis.
	 def full_title(page_title)
		base_title = "Lynkr"
		if page_title.empty?
			base_title
		else
			"#{page_title} | #{base_title}"
		end
	 end

	def avatar_url(user)
		gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
		return "http://gravatar.com/avatar/#{gravatar_id}.png"
	end

	def initials(user)
		name = user.first_name[0,1] + user.last_name[0,1]
	end
	
end

app/views/application/_sidebar.html.erb
<div class="sidebar left">
	
	<h2 class="logo">lynkr</h2>
	<i class="fa fa-times sidebar-close"></i>

	<%#= link_to 'lynkr', root_path, class: "logo" %>

	<div class="main-nav">

		<ul>
			<%= nav_link_to favourites_path  do %>
	                      		<li class="sidebar-links title-link"><p>favourites</p><i class="fa fa-star favourite-button"></i></li>
	                 	<% end %>

			<%= nav_link_to links_path  do %>
	                      		<li class="sidebar-links title-link"><p>all links</p></li>
	                 	<% end %>

	                 	<%= nav_link_to collections_path  do %>
	                      		<li class="sidebar-links title-link"><p>dock</p></li>
	                 	<% end %>

		</ul>

		<ul class="sidebar-collection-links-wrapper">

			<% @sidebar_collections.reverse.each do |collection| %>

				<%= nav_link_to browse_path(collection) do %>

					<li class="sidebar-collection-links"><p><%= collection.title %></p></li>

				<% end %>

	                 	<% end %>
			
		</ul>

	</div>


	<div class="footer group">

		<a href="mailto:jclackett@gmail.com" target="_top" class="left">Email Us!</a>

		<p class="right" >&copy; Lynkr 2015</p>	

	</div>

</div>

app/views/application/_top_bar.html.erb
<header class="top-bar right">

	<div class="top-section">

		<i class="fa fa-bars"></i>

		<%= render '/collections/breadcrumbs' , collection: @current_collection %>


<!-- 		<div class="search-wrapper">

				<i class="fa fa-search search-icon"></i>

				<form action="<%= root_path %>" method="get" class="search-form" >

					<%= text_field_tag :q, params[:s], placeholder: "Search", class: "search-input"%>
					<%= submit_tag "Search", :style => "display: none;", :name  => nil %>

				</form>

		</div>
 -->	
		<div class="login-section right">


		           <div class="current-user" >

		           	<div class="user-initials">
		           		<!-- Need to make Users Controller -->
		           	</div>

		           	<%= gravatar_image_tag(current_user.email.gsub('spam', 'mdeering'), :alt => current_user.first_name) if current_user %>

		           	<%= image_tag("guest.png", :alt => "Guest") unless current_user %>

		           </div>

		           <div class="user-popup">

		                     	<%= link_to 'logout', destroy_user_session_path, method: :delete %>

		           </div>	

		</div>
	
	</div>

	
	<div class="bottom-section">

			<% if @current_collection %> <!-- This is for the new collection/link , not in sub collection -->

				<% if current_page?(:controller => "collections", :action => "browse") %> <!-- To Stop showing on New/edit pages for sub link etc -->

					<div class="topbar-links">

						<%= nav_link_to new_sub_link_path(@current_collection)  do %>
			                      			<p>add link</p>
			                 		<% end %>

				                 	<%= nav_link_to new_sub_collection_path(@current_collection)  do %>
				                      		<p>add collection</p>
				                 	<% end %>

			                 	</div>

					<div class="section-header">

						<%= best_in_place @current_collection, :title, :as => :input , :class => "best_in_place_title" %>

						<i class="fa fa-caret-down collection-extras">


							<div class="collection-extras-popup hidden">

								<ul>

									<%= link_to "#", :collection_id => @current_collection.id, :collection_title => @current_collection.title , class: "share-collection" do %>
										
										<li>
											<i class="fa fa-share"></i>

											<p>Share Collection</p>
										</li>

									<% end %>

									<% if current_user.id == @current_collection.user_id %>
									
										<%= link_to @current_collection, method: :delete, data: { confirm: 'Are you sure?' }  do %>

											<li>

												<i class="fa fa-times"></i>

												<p>Unfollow Collection</p>

											</li>

										<% end %>

									<% else %>	

										<%= link_to unfollow_collection_path(@current_collection), method: :delete, data: { confirm: 'Are you sure?' } do %>
											
											<li>
												<i class="fa fa-sign-out"></i>

												<p>Unfollow Collection</p>
											</li>

										<% end %>

									<% end %>

								</ul>

							</div>

						</i>
					</div>	

					<div class="shared-icons">

						<!-- shared with users -->
						<% @shared_collections_current_filtered.each do |shared_with| %>
							<div class="shared-user">
								<%= gravatar_image_tag(shared_with.shared_user.email.gsub('spam', 'mdeering'), :alt => shared_with.shared_user.first_name) %>
								<p><%= initials(shared_with.shared_user) %></p>
							</div>
						<% end %>

						<% unless @current_collection.user_id == nil %>
							<!-- creator -->
							<div class="shared-user creator-user">
								<%= gravatar_image_tag(@current_collection.user.email.gsub('spam', 'mdeering'), :alt => @current_collection.user.first_name) %> 
								<p><%= initials(@current_collection.user) %></p>
							</div>
						<% end %>

					</div>

				<% else %>

					<div class="section-header">

						<span><%= @bottom_bar_header %></span>

					<div class="section-header">

				<% end %>
				
			<% elsif current_page?('/') || current_page?('/collections') %>

				<div class="topbar-links">

					<%= nav_link_to new_link_path  do %>
		                      			<p>add link</p>
		                 		<% end %>

			                 	<%= nav_link_to new_collection_path  do %>
			                      		<p>add collection</p>
			                 	<% end %>

		                 	</div>

				<div class="section-header">

					<span><%= @bottom_bar_header %></span>

				</div>

			<% else %>

				<div class="section-header">

					<span><%= @bottom_bar_header %></span>

				</div>

			<% end %>

		</div>
	
	</div>

</header>