config/routes.rb
Rails.application.routes.draw do

  # ----------------------------------------------------------
    # Links
  # ----------------------------------------------------------

  resources :links , except: [:edit, :show ] do
    member do
      get 'favourite'
      get 'update_description'
    end
  end
  get 'favourites' => 'links#favourites'
  
  # ----------------------------------------------------------
    # Collections
  # ----------------------------------------------------------

  resources :collections, except: [:edit, :show ] do
    member do
      get 'pin'
      delete 'unfollow'
    end
  end

  get "browse/:collection_id" => "collections#browse", :as => "browse"
  get "browse/:collection_id/new_collection" => "collections#new", :as => "new_sub_collection"
  get "browse/:collection_id/new_link" => "links#new", :as => "new_sub_link"

  post "collection/share" => "collections#share"

  # ----------------------------------------------------------
    # Devise
  # ----------------------------------------------------------

  devise_for :users
  devise_scope :user do 
      get 'register', to: "devise/registrations#new"
      get 'login', to: "devise/sessions#new"
  end

  # ----------------------------------------------------------
    # Where users go upon opening site
  # ----------------------------------------------------------

  authenticated :user do
    get '/', to: "collections#index"
  end
  unauthenticated :user do
    root to: 'static_pages#home' 
  end

  # ----------------------------------------------------------
    # Static Pages
  # ----------------------------------------------------------
  get 'home' => 'static_pages#home', as: :home


end

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href="/favicon.ico" rel="shortcut icon" type="image/x-icon" />

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-61689013-2', 'auto');
  ga('send', 'pageview');

</script>
  
</head>

app/views/layouts/application.html.erb
<%= render 'layouts/header' %>
<body class="group l-application">

	<%= render 'sidebar' %>
	<%= render 'top_bar' %>

	<div class="main-content">
	
		<div id="flash_messages">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			 <% end %>
		</div>

		<%= yield %>
	</div>



<script>
    peekin = {api_key: "0beed13adbba75d3d990"};
    // If you'd like to identify the user, uncomment the following line:
    peekin.identity = <%= current_user.first_name if current_user%>;
</script>
<script src="//api.peekin.io/peekin.js" async></script>


</body>

</html>

app/views/layouts/devise.html.erb
<%= render 'layouts/header' %>

<body class="l-devise">

	<%= yield %>

</body>

app/views/layouts/landing.html.erb
<%= render 'layouts/header' %>

<body class="l-landing">

	<header class="top-bar">

		<%= link_to 'lynkr', root_url, class: 'logo' %>

		<nav class="main-nav">

			<ul>
				<% unless user_signed_in? %>
					<li><%= link_to "login", login_path, class: "login-button" %></li>
					<li><%= link_to "register", register_path, class: "register-button" %></li>
				<% end %>
			</ul>

		</nav>

	</header>

	<%= yield %>

	<div class="signup-banner">

		<div class="content-wrapper">

			<p>Start sharing your links today</p>

			<%= link_to "sign up now", register_path, class: "" %>

		</div>

	</div>

	<footer class="landing-footer">

		<ul class="footer-element">
			<li><a href="http://www.facebook.com/lynkr" target="_blank">Facebook</a></li>
			<li><a href="http://www.twitter.com/lynkr" target="_blank">Twitter</a></li>
		</ul>

	</footer>

</body>
</html>